name: IkemdiFrontBuild

on: [push]

jobs:
  build:
    runs-on: linuxpskz
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker-compose
        run: docker-compose up -f ./app/docker-compose.yml -d 
    
