name: IkemdiFrontBuild

on: [push]

jobs:
  build:
    runs-on: linuxpskz
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./app/docker-compose.yml"
      # - name: Building the app
      #   env:
      #     CI: ""
      #   run: echo ${{ secrets.USERPWD }} | sudo -S systemctl restart ikemdi.service 
